all:
  hosts:
    node1:
      ansible_host: 162.19.71.6
      #ip: 192.168.250.128
      access_ip: 162.19.71.6
      ansible_user: ubuntu
    node2:
      ansible_host: 57.128.83.179
      #ip: 10.10.1.4
      access_ip: 57.128.83.179
      ansible_user: ubuntu
    node3:
      ansible_host: 141.94.107.102
      #ip: 10.10.1.5
      access_ip: 141.94.107.102
      ansible_user: ubuntu
  children:
    kube_control_plane:
      hosts:
        node1:
    kube_node:
      hosts:
        node2:
        node3:
    etcd:
      hosts:
        node1:
        node2:
        node3:
    k8s_cluster:
      children:
        kube_control_plane:
        kube_node:
    calico_rr:
      hosts: {}
